import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../core/market_colors.dart';
import '../providers/market_providers.dart';
import '../widgets/products/wishlist_button.dart';
import '../widgets/market/flash_sale_timer.dart';

class MarketHomePage extends ConsumerStatefulWidget {
  const MarketHomePage({super.key});
  @override ConsumerState<MarketHomePage> createState() => _MarketHomePageState();
}

class _MarketHomePageState extends ConsumerState<MarketHomePage> {
  final _scroll = ScrollController();
  final _bannerCtrl = PageController(viewportFraction: 0.94);
  Timer? _timer;
  int _currentBanner=0;
  int _selectedNav=0;

  @override void initState(){ super.initState(); _scroll.addListener(()=> _onScroll()); }
  void _onScroll(){ if(_scroll.position.pixels > _scroll.position.maxScrollExtent - 600) ref.read(forYouProvider.notifier).loadMore(); }
  @override void dispose(){ _scroll.dispose(); _bannerCtrl.dispose(); _timer?.cancel(); super.dispose(); }

  void _startAuto(int c){ _timer?.cancel(); if(c<=1) return; _timer=Timer.periodic(const Duration(seconds:5), (_){ if(!_bannerCtrl.hasClients) return; _currentBanner=(_currentBanner+1)%c; _bannerCtrl.animateToPage(_currentBanner, duration: const Duration(milliseconds:600), curve: Curves.easeOut); }); }

  String _shopName(Map<String,dynamic> p) => (p['shop_name']??'Boutique THIX').toString();
  double _price(dynamic v){ if(v is num) return v.toDouble(); return double.tryParse(v?.toString()??'')??0; }
  Widget _img(String? url){ if(url==null||url.isEmpty) return Container(color: MarketColors.lightBg, child: const Icon(Icons.image_outlined, color: MarketColors.mutedText)); return Image.network(url, fit: BoxFit.cover, cacheWidth: 500, errorBuilder: (_,__,___)=> Container(color: MarketColors.lightBg, child: const Icon(Icons.broken_image_outlined)), loadingBuilder: (c,ch,pr)=> pr==null?ch:Container(color: MarketColors.lightBg)); }

  @override Widget build(BuildContext context){
    final bannersAsync = ref.watch(bannersProvider);
    final flashAsync = ref.watch(flashSalesProvider);
    final forYouAsync = ref.watch(forYouProvider);
    final all = ref.watch(allMarketProductsProvider);
    bannersAsync.whenData((b)=> WidgetsBinding.instance.addPostFrameCallback((_)=> _startAuto(b.length)));

    return Scaffold(
      backgroundColor: MarketColors.lightBg,
      body: RefreshIndicator(color: MarketColors.red, onRefresh: () async { ref.invalidate(bannersProvider); ref.invalidate(flashSalesProvider); await ref.read(forYouProvider.notifier).refresh(); }, child: CustomScrollView(controller: _scroll, slivers: [
        SliverToBoxAdapter(child: _topBar()),
        SliverToBoxAdapter(child: bannersAsync.when(loading: ()=> const SizedBox(height:230, child: Center(child: CircularProgressIndicator())), error: (_,__)=> const SizedBox.shrink(), data: (b)=> _banner(b))),
        SliverToBoxAdapter(child: _trust()),
        SliverToBoxAdapter(child: _search()),
        const SliverToBoxAdapter(child: SizedBox(height:24)),
        SliverToBoxAdapter(child: _shops()),
        const SliverToBoxAdapter(child: SizedBox(height:24)),
        SliverToBoxAdapter(child: _promoRow()),
        const SliverToBoxAdapter(child: SizedBox(height:20)),
        SliverToBoxAdapter(child: _b2b()),
        const SliverToBoxAdapter(child: SizedBox(height:20)),
        SliverToBoxAdapter(child: flashAsync.when(loading: ()=> const SizedBox.shrink(), error: (_,__)=> const SizedBox.shrink(), data: (f)=> f.isEmpty? const SizedBox.shrink() : _flash(f))),
        const SliverToBoxAdapter(child: SizedBox(height:24)),
        SliverToBoxAdapter(child: Padding(padding: const EdgeInsets.symmetric(horizontal:16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Tous les produits', style: TextStyle(fontWeight: FontWeight.w900, fontSize:16)), GestureDetector(onTap: (){}, child: const Text('Voir tout', style: TextStyle(color: MarketColors.red, fontSize:12, fontWeight: FontWeight.w800)))]))),
        const SliverToBoxAdapter(child: SizedBox(height:12)),
        forYouAsync.when(loading: ()=> const SliverToBoxAdapter(child: Padding(padding: EdgeInsets.all(60), child: Center(child: CircularProgressIndicator()))), error: (e,_ )=> SliverToBoxAdapter(child: Center(child: Text('Erreur $e'))), data: (_)=> SliverPadding(padding: const EdgeInsets.symmetric(horizontal:16), sliver: SliverGrid(delegate: SliverChildBuilderDelegate((_,i){ if(i>=all.length) return const Center(child: CircularProgressIndicator()); return _card(all[i]); }, childCount: all.length + (ref.read(forYouProvider.notifier).hasMore?1:0)), gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:0.62)))),
        const SliverToBoxAdapter(child: SizedBox(height:110)),
      ])),
      bottomNavigationBar: _bottomNav(),
    );
  }

  Widget _topBar()=> Container(color: MarketColors.white, padding: const EdgeInsets.fromLTRB(16,54,16,16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(children: [Container(width:44,height:44, decoration: BoxDecoration(borderRadius: BorderRadius.circular(14), border: Border.all(color: MarketColors.cardBorder)), child: const Icon(Icons.shopping_bag_rounded, color: MarketColors.red)), const SizedBox(width:10), const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('THIX MARKET', style: TextStyle(fontWeight: FontWeight.w900, fontSize:16)), Text('Achetez. Vendez. Évoluez.', style: TextStyle(fontSize:11, color: MarketColors.mutedText))])]), Row(children: [IconButton(icon: const Icon(Icons.notifications_none), onPressed: ()=> context.push('/market/notifications')), InkWell(onTap: ()=> context.push('/user/dashboard'), child: Container(width:40,height:40, decoration: const BoxDecoration(color: MarketColors.red, shape: BoxShape.circle), child: const Icon(Icons.person, color: Colors.white, size:20)))])]));
  Widget _trust()=> Container(color: MarketColors.white, padding: const EdgeInsets.all(12), child: const Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [Row(children: [Icon(Icons.lock_outline, size:14, color: MarketColors.red), SizedBox(width:4), Text('Paiement sécurisé', style: TextStyle(fontSize:10, fontWeight: FontWeight.w600))]), Row(children: [Icon(Icons.verified_user_outlined, size:14, color: MarketColors.red), SizedBox(width:4), Text('Vendeurs vérifiés', style: TextStyle(fontSize:10, fontWeight: FontWeight.w600))]), Row(children: [Icon(Icons.local_shipping_outlined, size:14, color: MarketColors.red), SizedBox(width:4), Text('Livraison fiable', style: TextStyle(fontSize:10, fontWeight: FontWeight.w600))])]));
  Widget _search()=> Container(color: MarketColors.white, padding: const EdgeInsets.all(16), child: GestureDetector(onTap: ()=> context.push('/market/search'), child: Container(height:48, padding: const EdgeInsets.symmetric(horizontal:16), decoration: BoxDecoration(borderRadius: BorderRadius.circular(24), border: Border.all(color: MarketColors.cardBorder)), child: const Row(children: [Icon(Icons.search, color: MarketColors.red, size:20), SizedBox(width:10), Text('Rechercher un produit, marque...', style: TextStyle(color: MarketColors.mutedText, fontSize:13))]))));
  Widget _shops(){ final shopsAsync=ref.watch(featuredShopsProvider); return Padding(padding: const EdgeInsets.symmetric(horizontal:16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Supermarchés à domicile', style: TextStyle(fontWeight: FontWeight.w900, fontSize:16)), GestureDetector(onTap: ()=> context.push('/market/shops'), child: const Text('Tout voir', style: TextStyle(color: MarketColors.red, fontSize:12, fontWeight: FontWeight.w800)))]), const SizedBox(height:16), shopsAsync.when(loading: ()=> const SizedBox(height:60, child: Center(child: CircularProgressIndicator())), error: (_,__)=> const SizedBox.shrink(), data: (shops)=> Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: shops.take(4).map((s)=> GestureDetector(onTap: ()=> context.push('/market/shop/${s['id']}'), child: Column(children: [Container(height:64,width:64, decoration: BoxDecoration(shape: BoxShape.circle, color: MarketColors.red, image: s['logo_url']!=null? DecorationImage(image: NetworkImage(s['logo_url']), fit: BoxFit.cover):null), child: s['logo_url']==null? const Icon(Icons.storefront_rounded, color: Colors.white, size:28):null), const SizedBox(height:8), Text((s['name']??'Shop').toString(), style: const TextStyle(fontSize:11.5, fontWeight: FontWeight.w700))]))).toList()))])); }
  Widget _banner(List<Map<String,dynamic>> banners){ final slides = banners.isEmpty? [null] : banners; return Column(children: [SizedBox(height:230, child: PageView.builder(controller: _bannerCtrl, itemCount: slides.length, onPageChanged: (i)=> _currentBanner=i, itemBuilder: (_,i){ final b=slides[i] as Map<String,dynamic>?; return Container(margin: const EdgeInsets.symmetric(horizontal:6), padding: const EdgeInsets.all(22), decoration: BoxDecoration(borderRadius: BorderRadius.circular(24), gradient: const LinearGradient(colors: [MarketColors.redDark, MarketColors.red])), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text(b?['title']??'Votre marketplace\npremium', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w900, fontSize:20)), const SizedBox(height:8), Text(b?['subtitle']??'Des milliers de produits vérifiés', style: const TextStyle(color: Colors.white70, fontSize:12)), const SizedBox(height:16), Container(padding: const EdgeInsets.symmetric(horizontal:18,vertical:12), decoration: BoxDecoration(color: MarketColors.gold, borderRadius: BorderRadius.circular(14)), child: const Text('Explorer le marché', style: TextStyle(color: MarketColors.redDark, fontWeight: FontWeight.w800, fontSize:12)))])); })), const SizedBox(height:10), Row(mainAxisAlignment: MainAxisAlignment.center, children: List.generate(slides.length, (i){ final active=i==_currentBanner; return AnimatedContainer(duration: const Duration(milliseconds:250), margin: const EdgeInsets.symmetric(horizontal:3), height:6, width:active?18:6, decoration: BoxDecoration(color: active?MarketColors.red:Colors.grey.shade300, borderRadius: BorderRadius.circular(10))); }))]); }
  Widget _promoRow()=> Padding(padding: const EdgeInsets.symmetric(horizontal:16), child: Row(children: [Expanded(child: GestureDetector(onTap: ()=> context.push('/market/flash-sales'), child: Container(height:150, padding: const EdgeInsets.all(16), decoration: BoxDecoration(gradient: const LinearGradient(colors: [MarketColors.redDark, MarketColors.red]), borderRadius: BorderRadius.circular(20)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('OFFRES EXCLUSIVES', style: TextStyle(color: MarketColors.gold, fontSize:10, fontWeight: FontWeight.w800)), const SizedBox(height:6), const Text('Jusqu\'à -50%', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w900, fontSize:19)), const Spacer(), Container(padding: const EdgeInsets.symmetric(horizontal:12,vertical:8), decoration: BoxDecoration(color: MarketColors.gold, borderRadius: BorderRadius.circular(10)), child: const Text('Découvrir', style: TextStyle(color: MarketColors.redDark, fontWeight: FontWeight.w800, fontSize:11)))])))), const SizedBox(width:12), Expanded(child: GestureDetector(onTap: ()=> context.push('/market/vendor/dashboard'), child: Container(height:150, padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: MarketColors.creamBg, borderRadius: BorderRadius.circular(20)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('VENDEZ AVEC THIX', style: TextStyle(color: Color(0xFFC9862B), fontSize:10, fontWeight: FontWeight.w800)), const SizedBox(height:6), const Text('Développez votre\nbusiness', style: TextStyle(fontWeight: FontWeight.w900, fontSize:15)), const Spacer(), Container(padding: const EdgeInsets.symmetric(horizontal:12,vertical:8), decoration: BoxDecoration(color: MarketColors.gold, borderRadius: BorderRadius.circular(10)), child: const Text('Commencer', style: TextStyle(color: MarketColors.redDark, fontWeight: FontWeight.w800, fontSize:11)))]))))]));
  Widget _b2b(){ final tools=[{'icon':Icons.compare_arrows_rounded,'label':'Comparer','path':'/market/compare'},{'icon':Icons.notifications_active_rounded,'label':'Alerte Prix','path':'/market/price-alerts'},{'icon':Icons.request_quote_rounded,'label':'Devis B2B','path':'/market/b2b'},{'icon':Icons.favorite_rounded,'label':'Wishlist','path':'/market/wishlist'}]; return Padding(padding: const EdgeInsets.symmetric(horizontal:16), child: Container(padding: const EdgeInsets.symmetric(vertical:14,horizontal:8), decoration: BoxDecoration(color: MarketColors.white, borderRadius: BorderRadius.circular(16)), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: tools.map((t)=> InkWell(onTap: ()=> context.push(t['path'] as String), child: Column(children: [Icon(t['icon'] as IconData, color: MarketColors.red, size:24), const SizedBox(height:6), Text(t['label'] as String, style: const TextStyle(fontSize:10, fontWeight: FontWeight.w800))]))).toList()))); }
  Widget _flash(List<dynamic> list)=> Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: const EdgeInsets.symmetric(horizontal:16), child: Row(children: [const Icon(Icons.bolt_rounded, color: MarketColors.gold, size:22), const SizedBox(width:6), const Text('Offres flash', style: TextStyle(fontWeight: FontWeight.w900, fontSize:18)), const Spacer(), FlashSaleTimer(endTime: DateTime.now().add(const Duration(hours:2)))])), const SizedBox(height:12), SizedBox(height:245, child: ListView.separated(padding: const EdgeInsets.symmetric(horizontal:16), scrollDirection: Axis.horizontal, itemCount: list.length, separatorBuilder: (_,__)=> const SizedBox(width:12), itemBuilder: (_,i)=> SizedBox(width:155, child: _card(list[i] as Map<String,dynamic>))))]);
  Widget _card(Map<String,dynamic> p){ final price=_price(p['discount_price']??p['price']); final orig=_price(p['price']); final hasDisc=price<orig && price>0; final img=(p['image_url']?? (p['images'] is List && (p['images'] as List).isNotEmpty? (p['images'] as List).first : null)) as String?; return GestureDetector(onTap: ()=> context.push('/market/product/${p['id']}'), child: Container(decoration: BoxDecoration(color: MarketColors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: MarketColors.cardBorder)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(flex:5, child: Stack(fit: StackFit.expand, children: [ClipRRect(borderRadius: const BorderRadius.vertical(top: Radius.circular(18)), child: _img(img)), if(hasDisc) Positioned(top:8,left:8, child: Container(padding: const EdgeInsets.symmetric(horizontal:6,vertical:4), decoration: BoxDecoration(color: MarketColors.red, borderRadius: BorderRadius.circular(8)), child: Text('-${((1-price/orig)*100).round()}%', style: const TextStyle(color: Colors.white, fontSize:10, fontWeight: FontWeight.w900)))), Positioned(top:6,right:6, child: Container(padding: const EdgeInsets.all(4), decoration: const BoxDecoration(color: Colors.white, shape: BoxShape.circle), child: WishlistButton(productId: p['id'].toString(), size:20)))] )), Expanded(flex:5, child: Padding(padding: const EdgeInsets.all(10), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(p['title']??'', maxLines:2, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize:12, fontWeight: FontWeight.w700)), const Spacer(), Text('${price.toInt()} FC', style: const TextStyle(fontWeight: FontWeight.w900, fontSize:14, color: MarketColors.red)), Text(_shopName(p), maxLines:1, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize:10, color: MarketColors.mutedText))])))] ))); }
  Widget _bottomNav(){ return Container(color: MarketColors.white, padding: const EdgeInsets.only(top:6), child: SafeArea(top:false, child: SizedBox(height:64, child: Stack(clipBehavior: Clip.none, alignment: Alignment.center, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [_navItem(Icons.home_rounded,'Accueil',0), _navItem(Icons.receipt_long_rounded,'Commandes',1), const SizedBox(width:60), _navItem(Icons.favorite_rounded,'Wishlist',3), _navItem(Icons.notifications_active_rounded,'Alertes',4)]), Positioned(top:-20, child: GestureDetector(onTap: ()=> context.push('/market/cart'), child: Container(width:60,height:60, alignment: Alignment.center, decoration: BoxDecoration(color: MarketColors.red, shape: BoxShape.circle, border: Border.all(color: Colors.white, width:4)), child: const Icon(Icons.shopping_bag_rounded, color: Colors.white, size:26))))]))); }
  Widget _navItem(IconData icon, String label, int index){ final sel=_selectedNav==index; return GestureDetector(onTap: (){ setState(()=> _selectedNav=index); if(index==0){ _scroll.animateTo(0, duration: const Duration(milliseconds:400), curve: Curves.easeOut); } if(index==1) context.push('/market/orders'); if(index==3) context.push('/market/wishlist'); if(index==4) context.push('/market/price-alerts'); }, child: Container(width:65, padding: const EdgeInsets.symmetric(vertical:4), child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(icon, color: sel?MarketColors.red:MarketColors.mutedText, size:24), const SizedBox(height:2), Text(label, maxLines:1, style: TextStyle(fontSize:10, color: sel?MarketColors.red:MarketColors.mutedText, fontWeight: sel?FontWeight.w800:FontWeight.w500))]))); }
}
