// lib/presentation/thix_sante/patient/screens/trouver_hopital_page.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/thix_sante_colors.dart';
class TrouverHopitalPage extends ConsumerStatefulWidget { const TrouverHopitalPage({super.key}); @override ConsumerState<TrouverHopitalPage> createState()=>_TrouverHopitalPageState(); }
class _TrouverHopitalPageState extends ConsumerState<TrouverHopitalPage> {
  String f='Tous'; final all=[{'nom':'Hôpital Général','type':'Public','dist':'0.8 km','wait':'15 min','rating':4.7,'open':true},{'nom':'Clinique Diamant','type':'Privé','dist':'1.4 km','wait':'5 min','rating':4.9,'open':true},{'nom':'Centre Médical Gombe','type':'Public','dist':'2.1 km','wait':'25 min','rating':4.3,'open':false}];
  @override Widget build(BuildContext c){
    final list=f=='Tous'?all:all.where((e)=>e['type']==f).toList();
    return Scaffold(backgroundColor: ThixSanteColors.background, appBar: AppBar(backgroundColor: Colors.white, title: const Text('Hôpitaux', style: TextStyle(fontWeight: FontWeight.w800)), leading: IconButton(icon: const Icon(Icons.arrow_back), onPressed: ()=>Navigator.pop(context)), bottom: PreferredSize(preferredSize: const Size.fromHeight(110), child: Padding(padding: const EdgeInsets.all(16), child: Column(children: [TextField(decoration: InputDecoration(hintText: 'Rechercher hôpital, spécialité...', prefixIcon: const Icon(Icons.search), filled: true, fillColor: Colors.white, border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none))), const SizedBox(height:10), Row(children: ['Tous','Public','Privé'].map((t)=> Padding(padding: const EdgeInsets.only(right:8), child: ChoiceChip(label: Text(t), selected: f==t, onSelected: (_)=>setState(()=>f=t)))).toList())])))), body: ListView.builder(padding: const EdgeInsets.all(16), itemCount: list.length, itemBuilder: (_,i){final h=list[i]; return Card(margin: const EdgeInsets.only(bottom:12), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)), child: ListTile(leading: Container(width:52, height:52, decoration: BoxDecoration(color: ThixSanteColors.primarySurface, borderRadius: BorderRadius.circular(12)), child: const Icon(Icons.local_hospital, color: ThixSanteColors.primary)), title: Text(h['nom'] as String, style: const TextStyle(fontWeight: FontWeight.w800)), subtitle: Text('${h['type']} • ${h['dist']} • Attente ${h['wait']}\n⭐ ${h['rating']} • ${h['open']==true?'Ouvert':'Fermé'}'), isThreeLine: true, trailing: const Icon(Icons.directions, color: ThixSanteColors.primary), onTap: (){}));}));
  }
}
